# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts
RUN npm install typescript@^5.0.0 --no-save
COPY src ./src
RUN npm run build
ENV NODE_ENV=production
CMD ["node","build/index.js"]
